[workspace]
resolver = "2"
members = [
  "libs/core",
  "libs/storage",
  "libs/storage-core",
  "libs/storage-git",
  "libs/dbus-interface",
  "libs/cli",
  "libs/patronus",
  "libs/config",
  "libs/git-document-db",
  #"libs/gui/src-tauri",
]
