[workspace]
resolver = "2"
members = [
  "libs/cli",
  "libs/daemon",
  "libs/patronus",
  "libs/dbus",
  "libs/wrap-builder",
  "libs/window-tracker",
]

[workspace.lints.clippy]
unwrap_used = "warn"
expect_used = "warn"
